name: Run the unit tests & publish Docker image
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  # ───────────────────────────────────────── tests ──────────────────────────
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-dependencies
      - name: Run pytest
        run: pytest

  # ─────────────────────────────── database migrations ──────────────────────
  runmigrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-dependencies
      - name: Run django migrate
        run: python manage.py migrate

  migrations-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-dependencies
      - name: Run makemigrations --check
        run: python manage.py makemigrations --check

  # ───────────────────────────── docker build & push ────────────────────────
  build-docker-image:
    runs-on: ubuntu-latest
    needs: [test, runmigrations, migrations-check]
    # only trigger on direct pushes to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: devops-diploma-2025

    steps:
      - uses: actions/checkout@v4

      # ── derive lower‑case owner and expose as output ─────────────
      - name: Derive image owner
        id: prep
        run: echo "image_owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      # ── login ────────────────────────────────────────────────────
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ steps.prep.outputs.image_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ── OCI labels ───────────────────────────────────────────────
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.prep.outputs.image_owner }}/${{ env.IMAGE_NAME }}

      # ── build & push ─────────────────────────────────────────────
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.prep.outputs.image_owner }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
