name: Run the unit tests & publish Docker image
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  # ────────────────────────────────────────────────────────────────
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-dependencies

      - name: Run pytest
        run: pytest

  # ────────────────────────────────────────────────────────────────
  runmigrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-dependencies
      - name: Run django migrate
        run: python manage.py migrate

  # ────────────────────────────────────────────────────────────────
  migrations-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-dependencies
      - name: Run makemigrations --check
        run: python manage.py makemigrations --check

  # ────────────────────────────────────────────────────────────────
  build-docker-image:
    runs-on: ubuntu-latest
    needs: [ test, runmigrations, migrations-check ]
    if: github.ref == 'refs/heads/main'      # only build from main
    permissions:
      contents: read          # checkout
      packages: write         # push to GHCR
      id-token: write         # provenance
      attestations: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: devops-diploma-2025       # short image name
    steps:
      - uses: actions/checkout@v4

      # ── Login to your own GHCR namespace ────────────────────────
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}      
          password: ${{ secrets.GHCR_PAT }}             # PAT with write:packages

      # ── Optional metadata labels (kept) ─────────────────────────
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

      # ── Build & push ────────────────────────────────────────────
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
